const express = require('express');
const router = express.Router();
const loginRouter = require('./login');
const homeRouter = require('./home');
const productRouter = require('./product-admin');
const orderRouter = require('./order');
const orderComfirmRouter = require('./order-comfirm');
const orderCancelRouter = require('./order-cancel');
const orderShippingRouter = require('./order-shipping');
const orderCompleteRouter = require('./order-complete');
const createAdminRouter = require('./create-admin');
const updateAdminRouter = require('./update-admin');
const detailorderAdminRouter = require('./detail-order');
const detailcomfirmAdminRouter = require('./detail-comfirm');
const detailshippingAdminRouter = require('./detail-shipping');
const detailcompleteAdminRouter = require('./detail-complete');
const detailcancelAdminRouter = require('./detail-cancel');
const categoryRouter = require('./category');
const userAdminRouter = require('./userAdmin');
const likeAdminRouter = require('./likeAdmin');
const commentAdminRouter = require('./commentAdmin');
const paypalAdminRouter = require('./paypalAdmin');
const qrAdminRouter = require('./qrAdmin');
const staffAdminRouter = require('./staffAdmin');
const staffUpdateRouter = require('./staffUpdate');
const createStaffRouter = require('./createStaff');
const detailCommentRouter = require('./detailComment');
const createCategoryRouter = require('./createCategory');
const productsSoldRouter = require('./productsSold');
const productQualityRouter = require('./productQuality');
const profitDayRouter = require('./profitDay');
const detailQualityAdminRouter = require('./detailQuality');

router.use('/login',loginRouter);
router.use('/detailQuality',detailQualityAdminRouter);
router.use('/order',orderRouter);
router.use('/productQuality',productQualityRouter);
router.use('/profitDay',profitDayRouter);
router.use('/createCategory',createCategoryRouter);
router.use('/productsSold',productsSoldRouter);
router.use('/product-admin',productRouter);
router.use('/category-admin', categoryRouter);
router.use('/order-comfirm',orderComfirmRouter);
router.use('/order-cancel',orderCancelRouter);
router.use('/order-shipping',orderShippingRouter);
router.use('/order-complete',orderCompleteRouter);
router.use('/create-admin',createAdminRouter);
router.use('/update-admin',updateAdminRouter);
router.use('/detail-order',detailorderAdminRouter);
router.use('/detail-comfirm',detailcomfirmAdminRouter);
router.use('/detail-shipping',detailshippingAdminRouter);
router.use('/detail-complete',detailcompleteAdminRouter);
router.use('/detail-cancel',detailcancelAdminRouter);
router.use('/userAdmin',userAdminRouter);
router.use('/likeAdmin',likeAdminRouter);
router.use('/commentAdmin',commentAdminRouter);
router.use('/paypalAdmin',paypalAdminRouter);
router.use('/qrAdmin',qrAdminRouter);
router.use('/staffAdmin',staffAdminRouter);
router.use('/staffUpdate',staffUpdateRouter);
router.use('/createStaff',createStaffRouter);
router.use('/detailComment',detailCommentRouter);
router.use('/',homeRouter);
module.exports = router;