const express = require('express');
const router = express.Router();
const loginRouter = require('./login');
const homeRouter = require('./home');
const orderRouter = require('./order');
const orderConfirmRouter = require('./order-confirm');
const orderCancelRouter = require('./order-cancel');
const orderShippingRouter = require('./order-shipping');
const orderCompleteRouter = require('./order-complete');
const createAdminRouter = require('./create-admin');
const updateAdminRouter = require('./update-admin');
const detailorderAdminRouter = require('./detail-order');
const detailcomfirmAdminRouter = require('./detail-comfirm');
const detailshippingAdminRouter = require('./detail-shipping');
const detailcompleteAdminRouter = require('./detail-complete');
const detailcancelAdminRouter = require('./detail-cancel');
const categoryRouter = require('./category');

router.use('/login',loginRouter);
router.use('/order',orderRouter);
router.use('/category-admin', categoryRouter);
router.use('/order-confirm',orderConfirmRouter);
router.use('/order-cancel',orderCancelRouter);
router.use('/order-shipping',orderShippingRouter);
router.use('/order-complete',orderCompleteRouter);
router.use('/create-admin',createAdminRouter);
router.use('/update-admin',updateAdminRouter);
router.use('/detail-order',detailorderAdminRouter);
router.use('/detail-comfirm',detailcomfirmAdminRouter);
router.use('/detail-shipping',detailshippingAdminRouter);
router.use('/detail-complete',detailcompleteAdminRouter);
router.use('/detail-cancel',detailcancelAdminRouter);
router.use('/',homeRouter);
module.exports = router;